algoritmo "exercício02"
// Função :
// Autor :
// Data : 29/11/2022
// Seção de Declarações 
//2) Faça um programa que leia o nome de uma pessoa e mostre
//uma mensagem de boasvindas para ela:
//Ex: Qual é o seu nome? João da Silva
//Olá João da Silva, é um prazer te conhecer!
var
nome: caractere
inicio
escreva("Qual é o seu nome? ")
leia(nome)
escreva("Olá ",nome," é um prazer te conhecer!")


fimalgoritmo
