algoritmo "exercício08"
//9) Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
//e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.
var
dinheiroCarteira, converter : real

inicio

escreva("Digite quanto em dinheiro tem na carteira : ")
leia(dinheiroCarteira)

converter <- dinheiroCarteira / 3.45

escreva("Na cateira tenho R$ ",dinheiroCarteira," convertendo ele em dólares, dá : US$ ",converter)










fimalgoritmo
