algoritmo "exercício11"
//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.
var
dtrabalhados , total : real
inicio

escreval("Digite quantos dias o funcionário trabalhou no mês : ")
leia(dtrabalhados)

total <- dtrabalhados*(25*8)

escreval("A quantidade de dias trabalhados é de ",dtrabalhados)
escreval("seu salário e de R$ ",total)


fimalgoritmo

